import Head from "next/head";
import Image from "next/image";
import { Inter, Lato, Roboto } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Google from "../images/Google.png";
import { auth, firebase, googleAuthProvider } from "../lib/firebase";
import { toast } from "react-hot-toast";
import { StyleRegistry } from "styled-jsx";
import { useState, useRef, useContext, useEffect } from "react";
import { UserContext } from "../lib/context";
import RightPannel from "@/components/RightPannel/RightPannel";
import Profile from "@/components/Profiles/Profile";
const inter = Inter({ subsets: ["latin"] });
const lato = Lato({
  subsets: ["latin"],
  style: ["italic", "normal"],
  weight: ["400", "100"],
});

export default function Home() {
  // User Context
  const { user, username } = useContext(UserContext);

  // This is the Main Page of the website

  return (
    <>
      <Head>
        <title>🐈🐟</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* Left Side Panel */}
        <div className={styles.leftPanel}>{!user ? <Hero /> : null}</div>

        {/* Could we make this it's own components? */}
        {/* Right Side Panel */}
        <div className={styles.rightPanel}>
          {!user ? (
            <RightPannel />
          ) : (
            <>
              <div className="flex w-full h-full justify-between flex-col items-center">
                <h1 className="font-lato text-2xl mt-2 ">
                  Hi <span className="capitalize">{user.displayName}</span>
                </h1>

                <SignOutButton />
              </div>
            </>
          )}
        </div>
      </main>
    </>
  );
}

function GoogleSignUp() {
  // This is the sign in with google function
  const signInWithGoogle = async () => {
    await auth
      .signInWithPopup(googleAuthProvider)
      .then(() => {
        toast.success("Signed in");
      })
      .catch((error) => {
        console.log(error.message);
      });
  };
  return (
    <button className={styles.SWIGoogle} onClick={signInWithGoogle}>
      <Image src={Google} width={50} height={50} alt="Sign in with google" />
      Sign in Google
    </button>
  );
}

function SignOutButton() {
  return <button onClick={() => auth.signOut()}>Sign Out</button>;
}

function Hero() {
  return (
    <>
      <h1 className="text-[50px] font-lato font-black italic">
        WELCOME TO CATFISH!
      </h1>
      <p className="font-raleway tracking-wide">
        In this social media-inspired game, players work together to catch the
        elusive catfish, but be careful - not everyone is who they claim to be!
      </p>
      <p className="font-raleway tracking-wide">
        Analyze messages, photos, and participate in minigames to expose the
        fake profiles and emerge victorious.
      </p>
      <h2 className="font-lato italic">
        DO YOU HAVE WHAT IT TAKES TO CATCH THE CATFISH?
      </h2>
    </>
  );
}
